### ISSUE TITLE
Install is failing from npm

### ISSUE THREAD

**Issue by fusionstrings** [scottnonnenberg/eslint-compare-config#1]
First of all, thanks a lot for coming up with this idea.

While trying to install it gives following error to me.
`npm ERR! 404 no such package available : @scottnonnenberg/eslint-compare-config`

I'd install it from github

**Comment by scottnonnenberg** [comment]
Hm. It's definitely available publicly: https://www.npmjs.com/package/@scottnonnenberg/eslint-compare-config

Scoped packages do require a relatively recent version of `npm`. Can you give me the output of running these commands? 

```bash
node -v
npm -v
npm config ls
```

**Comment by scottnonnenberg** [comment]
With no response from you in 9 days, I'm closing this issue. Please feel free to reopen if you continue to have difficulties!

**Comment by fusionstrings** [comment]
I am sorry for getting back on this, I realise now that I was not able to install it because I've custom registry powered by [sinopia](https://github.com/rlidwka/sinopia), although it should have still worked.

Resetting registry to https://registry.npmjs.org/ enabled me to install it successfully.

In either case it's not issue from this package.

**Comment by scottnonnenberg** [comment]
You can install scoped packages through siniopia with this config change: https://github.com/rlidwka/sinopia/issues/376#issuecomment-195497794

**Comment by fusionstrings** [comment]
Thanks @scottnonnenberg It did work now 💯
