### ISSUE TITLE
Normalize the diffs

### ISSUE THREAD

**Issue by userpixel** [scottnonnenberg/eslint-compare-config#4]
I've been using this tool extensively for config-campatibility. Great tool but I noticed it shows some differences, where they are not considered to be different.
For example according to the [eslint config spec](http://eslint.org/docs/user-guide/configuring#configuring-rules), setting a value to `'error'` is the same as setting it to `['error']`. I get some diffs like this:

````
  no-constant-condition:
    left: 'warn'
    right: [ 'warn' ]
````

It can be great if those instances could be normalized automatically:

* if the config value is just one string, normalize it to an array with that string as its only element. The possible options are:

* `0`= `'off'` = `['off']`
* `1`= `'warn'` = `['warn']`
* `2`= `'error'` = `['error']`

**Comment by scottnonnenberg** [comment]
I like this. It'll be a relatively simple change inside of `fixRule`: https://github.com/scottnonnenberg/eslint-compare-config/blob/36a21347879fe3a60c9b95d2f5a40619739a8d2b/src/normalize_config.js#L18

Maybe you'd be interested in making the change?

**Comment by userpixel** [comment]
Will do 👍
